OnlineShop/Areas/Admin/Controllers/ProductAdminController.cs
using ASP_OnlineShopConnection;
using OnlineShop.Areas.Admin.BUS;
using OnlineShop.Areas.Admin.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Areas.Admin.Controllers
{
    public class ProductAdminController : Controller
    {
        // GET: Admin/Product
        public ActionResult Index()
        {
            var listProduct = ProductBUS.List();
            return View(listProduct);
        }

        // GET: Admin/Product/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/Product/Create
        public ActionResult Create()
        {
            ViewBag.MaLoaiSanPham = new SelectList(ProductBUS.GetListCategogy(), "MaLoaiSanPham", "TenLoaiSanPham");
            ViewBag.MaNhaCungCap = new SelectList(ProductBUS.GetListSupplier(), "MaNhaCungCap", "TenNhaCungCap");
            ViewBag.MaNhaSanXuat = new SelectList(ProductBUS.GetListManufacturer(), "MaNhaSanXuat", "TenNhaSanXuat");
            return View();
        }

        //POST: Admin/Product/Create
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(SanPham sp, HinhAnh ha)
        {
            try
            {
                // TODO: Add update logic here
                using (var db = new ASP_OnlineShopConnectionDB())
                {

                if (HttpContext.Request.Files.Count > 0)
                {
                    if(HttpContext.Request.Files.Count != 3)
                    {
                           return Content("<script language='javascript' type='text/javascript'>alert('Vui lòng chọn 3 hình sp!');</script>");
                     }
                    else
                    {
                            var hpf = HttpContext.Request.Files[0];
                            if (hpf.ContentLength > 0)
                            {
                                string fileName = Guid.NewGuid().ToString();
                                string nameImage = fileName + ".jpg";
                                string fullPathWithFileName = "/images/product/" + nameImage;
                                hpf.SaveAs(Server.MapPath(fullPathWithFileName));
                                sp.HinhUrl = nameImage;
                            }
                            db.Insert(sp);
                            var query = db.Query<SanPham>("SELECT * FROM SanPham ORDER BY MaSanPham DESC");
                            var id = query.First().MaSanPham;
                            for (int i = 0; i < 3; i++)
                            {
                                var hpf2 = HttpContext.Request.Files[i];
                                if (hpf2.ContentLength > 0)
                                {
                                    string fileName = Guid.NewGuid().ToString();
                                    string nameImage = fileName + ".jpg";
                                    string fullPathWithFileName = "/images/products/" + nameImage;
                                    hpf2.SaveAs(Server.MapPath(fullPathWithFileName));
                                    ha.TenHinhAnh = nameImage;
                                    ha.MaSanPham = id;
                                    db.Insert(ha);
                                }
                            }
                        }
                }

                //db.Update<SanPham>("SET TenSanPham=@0, GiaBan=@1, SoLuong=@2 WHERE MaSanPham=@3", sp.TenSanPham, sp.GiaBan, sp.SoLuong, id);
            }
                //Content("<script language='javascript' type='text/javascript'>alert('Thêm thành công!');</script>");
                return RedirectToAction("Index");
        }
        catch
        {
                //Content("<script language='javascript' type='text/javascript'>alert('Xảy ra lỗi!');</script>");
                return View(); //đây
        }
    }


        //public ActionResult Edit(int id)
        //{
        //    var sp = ProductBUS.ProductDetail(id);
        //    return View(sp);
        //}

        // GET: Admin/Product/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.MaLoaiSanPham = new SelectList(ProductBUS.GetListCategogy(), "MaLoaiSanPham", "TenLoaiSanPham");
            ViewBag.MaNhaCungCap = new SelectList(ProductBUS.GetListSupplier(), "MaNhaCungCap", "TenNhaCungCap");
            ViewBag.MaNhaSanXuat = new SelectList(ProductBUS.GetListManufacturer(), "MaNhaSanXuat", "TenNhaSanXuat");
            var sp = ProductBUS.ProductDetail(id);
            return View(sp);
        }

        // POST: Admin/Product/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, SanPham sp)
        {
            // TODO: Add update logic here
            using (var db = new ASP_OnlineShopConnectionDB())
            {
                db.Update<SanPham>("SET TenSanPham=@0, GiaBan=@1, SoLuong=@2, NgayNhap=@3, HinhUrl=@4, MoTa=@5, DaXoa=@6 WHERE MaSanPham=@7", sp.TenSanPham, sp.GiaBan, sp.SoLuong, sp.NgayNhap, sp.HinhUrl, sp.MoTa, sp.DaXoa, id);
            }
            return RedirectToAction("Index");
        }

        // GET: Admin/Product/Delete/5
        public ActionResult Delete(int id)
        {
            var info = new ProductInfoAdmin()
            {
                SanPhamInfoAdmim = ProductBUS.ProductDetail(id),
                TenLoaiSanPham = ProductBUS.GetTenLoaiSanPham(id),
                TenNhaCungCap = ProductBUS.GetTenNhaCungCap(id),
                TenNhaSanXuat = ProductBUS.GetTenNhaSanXuat(id)
            };
            return View(info);
            //var sp = ProductBUS.ProductDetail(id);
            //return View(sp);
        }

        // POST: Admin/Product/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                using (var db = new ASP_OnlineShopConnectionDB())
                {
                    //db.Delete("SanPham", id.ToString(), sp);
                    db.Update<SanPham>("SET DaXoa=1 WHERE MaSanPham=@0", id);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

OnlineShop/Areas/Admin/Controllers/ProductController.cs
using ASP_OnlineShopConnection;
using OnlineShop.Areas.Admin.BUS;
using OnlineShop.Areas.Admin.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        // GET: Admin/Product
        public ActionResult Index()
        {
            var listProduct = ProductBUS.List();
            return View(listProduct);
        }

        // GET: Admin/Product/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/Product/Create
        public ActionResult Create()
        {
            ViewBag.MaLoaiSanPham = new SelectList(ProductBUS.GetListCategogy(), "MaLoaiSanPham", "TenLoaiSanPham");
            ViewBag.MaNhaCungCap = new SelectList(ProductBUS.GetListSupplier(), "MaNhaCungCap", "TenNhaCungCap");
            ViewBag.MaNhaSanXuat = new SelectList(ProductBUS.GetListManufacturer(), "MaNhaSanXuat", "TenNhaSanXuat");
            return View();
        }

        //POST: Admin/Product/Create
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(SanPham sp, HinhAnh ha)
        {
            try
            {
                // TODO: Add update logic here
                using (var db = new ASP_OnlineShopConnectionDB())
                {

                if (HttpContext.Request.Files.Count > 0)
                {
                    if(HttpContext.Request.Files.Count != 3)
                    {
                           return Content("<script language='javascript' type='text/javascript'>alert('Vui lòng chọn 3 hình sp!');</script>");
                     }
                    else
                    {
                            var hpf = HttpContext.Request.Files[0];
                            if (hpf.ContentLength > 0)
                            {
                                string fileName = Guid.NewGuid().ToString();
                                string nameImage = fileName + ".jpg";
                                string fullPathWithFileName = "/images/product/" + nameImage;
                                hpf.SaveAs(Server.MapPath(fullPathWithFileName));
                                sp.HinhUrl = nameImage;
                            }
                            db.Insert(sp);
                            var query = db.Query<SanPham>("SELECT * FROM SanPham ORDER BY MaSanPham DESC");
                            var id = query.First().MaSanPham;
                            for (int i = 0; i < 3; i++)
                            {
                                var hpf2 = HttpContext.Request.Files[i];
                                if (hpf2.ContentLength > 0)
                                {
                                    string fileName = Guid.NewGuid().ToString();
                                    string nameImage = fileName + ".jpg";
                                    string fullPathWithFileName = "/images/products/" + nameImage;
                                    hpf2.SaveAs(Server.MapPath(fullPathWithFileName));
                                    ha.TenHinhAnh = nameImage;
                                    ha.MaSanPham = id;
                                    db.Insert(ha);
                                }
                            }
                        }
                }

                //db.Update<SanPham>("SET TenSanPham=@0, GiaBan=@1, SoLuong=@2 WHERE MaSanPham=@3", sp.TenSanPham, sp.GiaBan, sp.SoLuong, id);
            }
                //Content("<script language='javascript' type='text/javascript'>alert('Thêm thành công!');</script>");
                return RedirectToAction("Index");
        }
        catch
        {
                //Content("<script language='javascript' type='text/javascript'>alert('Xảy ra lỗi!');</script>");
                return View(); //đây
        }
    }


        //public ActionResult Edit(int id)
        //{
        //    var sp = ProductBUS.ProductDetail(id);
        //    return View(sp);
        //}

        // GET: Admin/Product/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.MaLoaiSanPham = new SelectList(ProductBUS.GetListCategogy(), "MaLoaiSanPham", "TenLoaiSanPham");
            ViewBag.MaNhaCungCap = new SelectList(ProductBUS.GetListSupplier(), "MaNhaCungCap", "TenNhaCungCap");
            ViewBag.MaNhaSanXuat = new SelectList(ProductBUS.GetListManufacturer(), "MaNhaSanXuat", "TenNhaSanXuat");
            var sp = ProductBUS.ProductDetail(id);
            return View(sp);
        }

        // POST: Admin/Product/Edit/5
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(int id, SanPham sp)
        {
            // TODO: Add update logic here
            using (var db = new ASP_OnlineShopConnectionDB())
            {
                db.Update<SanPham>("SET TenSanPham=@0, GiaBan=@1, SoLuong=@2, NgayNhap=@3, HinhUrl=@4, MoTa=@5, DaXoa=@6 WHERE MaSanPham=@7", sp.TenSanPham, sp.GiaBan, sp.SoLuong, sp.NgayNhap, sp.HinhUrl, sp.MoTa, sp.DaXoa, id);
            }
            return RedirectToAction("Index");
        }

        // GET: Admin/Product/Delete/5
        public ActionResult Delete(int id)
        {
            var info = new ProductInfoAdmin()
            {
                SanPhamInfoAdmim = ProductBUS.ProductDetail(id),
                TenLoaiSanPham = ProductBUS.GetTenLoaiSanPham(id),
                TenNhaCungCap = ProductBUS.GetTenNhaCungCap(id),
                TenNhaSanXuat = ProductBUS.GetTenNhaSanXuat(id)
            };
            return View(info);
            //var sp = ProductBUS.ProductDetail(id);
            //return View(sp);
        }

        // POST: Admin/Product/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                using (var db = new ASP_OnlineShopConnectionDB())
                {
                    //db.Delete("SanPham", id.ToString(), sp);
                    db.Update<SanPham>("SET DaXoa=1 WHERE MaSanPham=@0", id);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

OnlineShop/Controllers/ProductController.cs
using OnlineShop.BUS;
using OnlineShop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index(int page=1)
        {
            //var listProduct = ProductBUS.ListProduct(page, 3);
            return View();
        }

        public ActionResult Type(int id, int page = 1)
        {
            return View();
        }

        public ActionResult Producer(int id, int page = 1)
        {
            return View();
        }

        // GET: Product/Details/5
        public ActionResult Details(int id)
        {
            var info = new ProductInfo()
            {
                sanPham = ProductBUS.ProductDetail(id),
                arrHinhAnh = ProductBUS.listHinhAnh(id)
            };
            return View(info);
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Product/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Product/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Product/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Product/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Product/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

       
    }
}

OnlineShop/Areas/Admin/Views/Product/Create.cshtml
@model ASP_OnlineShopConnection.SanPham

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayout.cshtml";
}

<script src="~/Content/tinymce/js/tinymce/tinymce.min.js"></script>
<script>
    tinymce.init({
        selector: 'textarea',
        height: 200,
        menubar: false,
        plugins: [
          'advlist autolink lists link image charmap print preview anchor',
          'searchreplace visualblocks code fullscreen',
          'insertdatetime media table contextmenu paste code'
        ],
        toolbar: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
        content_css: '//www.tinymce.com/css/codepen.min.css'
    });
</script>

<h2>Create</h2>

@using (Html.BeginForm("Create", "ProductAdmin", FormMethod.Post, new { @enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SanPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.MaSanPham, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaSanPham, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaSanPham, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @*@Html.LabelFor(model => model.TenSanPham, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Tên sản phẩm</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSanPham, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.TenSanPham, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Giá bán</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Số lượng</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.LuotBinhChon, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Lượt bình chọn</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.LuotBinhChon, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.LuotBinhChon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.LuotBinhLuan, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Lượt bình luận</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.LuotBinhLuan, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.LuotBinhLuan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.LuotXem, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Lượt xem</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.LuotXem, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.LuotXem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.NgayNhap, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Ngày nhập</label>
            <div class="col-md-10">    
                @*@Html.EditorFor(model => model.NgayNhap, new { @class = "form-control", @value = DateTime.Now.ToShortDateString() })*@
                @*@Html.TextBoxFor(model => model.NgayNhap, new { @class = "form-control", type = "date", @Value = @DateTime.Now.ToShortDateString() })*@
                @Html.TextBoxFor(model => model.NgayNhap, new { @Value = @DateTime.Now.ToShortDateString(), @readonly = "readonly", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NgayNhap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.HinhUrl, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Hình ảnh</label>
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.HinhUrl, new { htmlAttributes = new { @class = "form-control" } })*@
                <input name="imgProduct" type="file" multiple="multiple" size="3" max="3" min="3" required="required" />
                @Html.ValidationMessageFor(model => model.HinhUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Mô tả</label>
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })*@
                @*<textarea name="Description" class="textarea"></textarea>*@
                @Html.TextAreaFor(model => model.MoTa, htmlAttributes: new { @class = "form-control", @rows = 5, @cols = 30, @name = "Description" })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.MaLoaiSanPham, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Loại sản phẩm</label>
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.MaLoaiSanPham, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownList("MaLoaiSanPham", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoaiSanPham, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.MaNhaCungCap, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Nhà cung cấp</label>
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.MaNhaCungCap, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownList("MaNhaCungCap", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNhaCungCap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.MaNhaSanXuat, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Hãng sản xuất</label>
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.MaNhaSanXuat, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownList("MaNhaSanXuat", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNhaSanXuat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.DaXoa, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Tình trạng</label>
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.DaXoa, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.DaXoa, new SelectList(
                  new List<Object>{
                       new { value = 0 , text = "Đang kinh doanh"  },
                       new { value = 1 , text = "Ngừng kinh doanh" },
                    },
                  "value",
                  "text",
                  new { htmlAttributes = new { @class = "form-control" } }))
                @Html.ValidationMessageFor(model => model.DaXoa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

OnlineShop/Areas/Admin/Views/Product/Delete.cshtml
@*@model ASP_OnlineShopConnection.SanPham*@
@model OnlineShop.Areas.Admin.ViewModels.ProductInfoAdmin

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @*@Html.DisplayNameFor(model => model.MaSanPham)*@
            @Html.DisplayName("Mã sản phẩm")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SanPhamInfoAdmim.MaSanPham)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.TenSanPham)*@
            @Html.DisplayName("Tên sản phẩm")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SanPhamInfoAdmim.TenSanPham)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.GiaBan)*@
            @Html.DisplayName("Giá bán")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SanPhamInfoAdmim.GiaBan)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.SoLuong)*@
            @Html.DisplayName("Số lượng")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SanPhamInfoAdmim.SoLuong)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.LuotBinhChon)*@
            @Html.DisplayName("Lượt bình chọn")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SanPhamInfoAdmim.LuotBinhChon)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.LuotBinhLuan)*@
            @Html.DisplayName("Lượt bình luận")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SanPhamInfoAdmim.LuotBinhLuan)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.LuotXem)*@
            @Html.DisplayName("Lượt xem")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SanPhamInfoAdmim.LuotXem)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.NgayNhap)*@
            @Html.DisplayName("Ngày nhập")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SanPhamInfoAdmim.NgayNhap)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.HinhUrl)*@
            @Html.DisplayName("Tên hình ảnh")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SanPhamInfoAdmim.HinhUrl)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.MoTa)*@
            @Html.DisplayName("Mô tả")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SanPhamInfoAdmim.MoTa)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.MaLoaiSanPham)*@
            @Html.DisplayName("Loại sản phẩm")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenLoaiSanPham)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.MaNhaCungCap)*@
            @Html.DisplayName("Nhà cung cấp")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNhaCungCap)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.MaNhaSanXuat)*@
            @Html.DisplayName("Hãng sản xuất")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNhaSanXuat)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.DaXoa)*@
            @Html.DisplayName("Tình trạng")
        </dt>

        <dd>
            @if (@Model.SanPhamInfoAdmim.DaXoa == 0)
            {
                @Html.DisplayName("Đang kinh doanh")
            }
            else
            {
                @Html.DisplayName("Ngừng kinh doanh")
            }
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>